---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/sufe/Documents/C++/CP-Program/CSES/Sorting_and_Searching/Sum_of_Two_Values.out'
relocations:
  - { offset: 0x23F2B, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0xB7D18, symBinAddr: 0x10000C0F8, symSize: 0x0 }
  - { offset: 0x24DDA, size: 0x8, addend: 0x0, symName: __ZL3dir, symObjAddr: 0xB7D00, symBinAddr: 0x10000C0E0, symSize: 0x0 }
  - { offset: 0x24E6D, size: 0x8, addend: 0x0, symName: _x, symObjAddr: 0xB7CF0, symBinAddr: 0x10000C0D0, symSize: 0x0 }
  - { offset: 0x24E84, size: 0x8, addend: 0x0, symName: _n, symObjAddr: 0xB7CE8, symBinAddr: 0x10000C0C8, symSize: 0x0 }
  - { offset: 0x24FBC, size: 0x8, addend: 0x0, symName: _v, symObjAddr: 0xB7CD0, symBinAddr: 0x10000C0B0, symSize: 0x0 }
  - { offset: 0x2517A, size: 0x8, addend: 0x0, symName: _m, symObjAddr: 0xB7CA0, symBinAddr: 0x10000C080, symSize: 0x0 }
  - { offset: 0x256E3, size: 0x8, addend: 0x0, symName: __GLOBAL__sub_I_Sum_of_Two_Values.cpp, symObjAddr: 0x800, symBinAddr: 0x1000075A0, symSize: 0x100 }
  - { offset: 0x25BD1, size: 0x8, addend: 0x0, symName: __ZNSt6vectorIxSaIxEED1Ev, symObjAddr: 0x1A8, symBinAddr: 0x1000073E8, symSize: 0x1C }
  - { offset: 0x25D4F, size: 0x8, addend: 0x0, symName: __ZNSt3mapIxxSt4lessIxESaISt4pairIKxxEEED1Ev, symObjAddr: 0x320, symBinAddr: 0x100007560, symSize: 0x3C }
  - { offset: 0x2721D, size: 0x8, addend: 0x0, symName: __ZNSt6vectorISt4pairIxxESaIS1_EED1Ev, symObjAddr: 0x1C4, symBinAddr: 0x100007404, symSize: 0x1C }
  - { offset: 0x273A0, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x3A0, symBinAddr: 0x1000076A0, symSize: 0x45C }
  - { offset: 0x286EF, size: 0x8, addend: 0x0, symName: __ZNSt8_Rb_treeIxSt4pairIKxxESt10_Select1stIS2_ESt4lessIxESaIS2_EE24_M_get_insert_unique_posERS1_.isra.0, symObjAddr: 0x0, symBinAddr: 0x100007240, symSize: 0xA0 }
  - { offset: 0x28870, size: 0x8, addend: 0x0, symName: __ZNSt8_Rb_treeIxSt4pairIKxxESt10_Select1stIS2_ESt4lessIxESaIS2_EE29_M_get_insert_hint_unique_posESt23_Rb_tree_const_iteratorIS2_ERS1_.isra.0, symObjAddr: 0xA0, symBinAddr: 0x1000072E0, symSize: 0x108 }
  - { offset: 0x28967, size: 0x8, addend: 0x0, symName: __ZNSt8_Rb_treeIxSt4pairIKxxESt10_Select1stIS2_ESt4lessIxESaIS2_EE8_M_eraseEPSt13_Rb_tree_nodeIS2_E.isra.0, symObjAddr: 0x1E0, symBinAddr: 0x100007420, symSize: 0x140 }
...
